version: '3'

services:
  sample:
    container_name: sample
    build:
      context: app-final/.
      dockerfile: Dockerfile
    volumes:
      - '.:/app-final/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    labels:
      kompose.service.type: LoadBalancer
    deploy:
      replicas: 3
    
  servidor1:
    build:
      context: Back/.
      dockerfile: Dockerfile
    volumes:
      - '.:/Back/app'
      - '/app/node_modules'
    ports:
      - "4200:4200"
    network_mode: host
    labels:
      kompose.service.type: LoadBalancer
    deploy:
      replicas: 3