version: '3'

services:
  sample:
    image: herbertreyes13j/finalfront:1.0
    build:
      context: app-final/.
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    labels:
      kompose.service.type: LoadBalancer
    deploy:
      replicas: 3
    
  servidor1:
    image: herbertreyes13j/finalback:1.0
    build:
      context: Back/.
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    network_mode: host
    labels:
      kompose.service.type: LoadBalancer
