apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: sample
  name: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: sample
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: sample
    spec:
      containers:
      - env:
        - name: CHOKIDAR_USEPOLLING
          value: "true"
        image: herbertreyes13j/finalfront:2.0
        imagePullPolicy: ""
        name: sample
        ports:
        - containerPort: 3000
        resources: {}
        stdin: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
