apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: servidor1
  name: servidor1
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: servidor1
    spec:
      containers:
      - image: servidor1
        name: servidor1
        ports:
        - containerPort: 4200
        resources: {}
        volumeMounts:
        - mountPath: /Back/app
          name: servidor1-claim0
        - mountPath: /app/node_modules
          name: servidor1-claim1
      restartPolicy: Always
      volumes:
      - name: servidor1-claim0
        persistentVolumeClaim:
          claimName: servidor1-claim0
      - name: servidor1-claim1
        persistentVolumeClaim:
          claimName: servidor1-claim1
status: {}
