apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.service.type: LoadBalancer
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: servidor1
  name: servidor1
spec:
  replicas: 3
  selector:
    matchLabels:
      io.kompose.service: servidor1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.service.type: LoadBalancer
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: servidor1
    spec:
      containers:
      - image: herbertreyes13j/finalback:5.0
        imagePullPolicy: ""
        name: servidor1
        ports:
        - containerPort: 4200
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
