version: '3.7'
volumes:
  mysql-db-data:
    name: mysql-db-data
services:
  db:
    image: mysql:latest 
    restart: always
    environment:
      MYSQL_DATABASE: 'ayd2_g6'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    build:
      dockerfile: Dockerfile
      context: ./mysql
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - 'mysql-db-data:/var/lib/mysql'

